#!/usr/bin/env bash
os=$(uname)
file=notes.yml
link=current

get_monday(){
if [[ $os == "Darwin" ]]; then
	date=$(date -v +Tues +"%Y-%m-%d")
elif [[ $os == "Linux" ]]; then
	date=$(date -d next-tuesday +"%Y-%m-%d")
else
	echo "$os not understood"
fi

if [[ "$date" == "$(date +"%Y-%m-%d")" ]]; then
	date=$(date -v +7d +"%Y-%m-%d")
fi
}

template(){
cat <<EOF > $date/$file
---

Website: http://open-nsm.net
Meeting Info: 6CT/7ET/4PT PM in 0216 Siebel Center on $date
Remote: '+1 (415) 762-9988 - Meeting ID: 419 334 147 <https://zoom.us/j/419334147>'
Mailing List: https://lists.illinois.edu/lists/subscribe/open-nsm
Facebook: https://www.facebook.com/groups/opennsmnow/
Github: https://github.com/open-nsm
Youtube: https://www.youtube.com/user/OpenNSM
Vimeo: https://vimeo.com/opennsm
IRC: ##opennsm on irc.freenode.net

Group Updates:
- TBA

Meeting Sections:
  Networking News:
  - TBA

  Conference Corner:
  - TBA

  Opportunity Outpost:
  - TBA

  Tool Trade:
  - TBA

  Paper Period:
  - TBA

  Signature Selection:
  - TBA

Talks:
  Small Talks:
    TBA:
    - TBA

  Big Talks:
    TBA:
    Website:
    Talk Details:
    Presenter:
EOF
}

get_monday
if ! [ -d $date ]
then
	mkdir $date && template
	ln -f -s $date/notes.yml current
	[ -f current ] && git add $date current && git commit -m "begin new meeting notes for $date" && git push

else
	echo "Meeting $date already exists"
	exit 1
fi

echo "Run notes.yml through a YAML parser before committing: http://www.yamllint.com/"
